---
root: true
ignorePatterns:
  - 'node_modules'
  - 'dist'
env:
  browser: true
  'es6': true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
  ecmaFeatures: {}
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'airbnb-typescript/base'
  - 'prettier'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
rules:
  no-underscore-dangle: ['error', { allowAfterThis: true }]
